#!/usr/bin/env node
/**
 * Generate docs/api.md from the live Express route table.
 *
 * Hand-written API docs drift. This walks the mounted routers, reads the
 * permission and module each guard declares on itself, and writes the
 * reference from what the app will actually serve. Run it with:
 *
 *   npm run docs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const app = (await import('../src/app.js')).createApp();
const { getModule } = await import('@erp/shared');

/** Express stores the mount path as a regexp; recover the literal prefix. */
function mountPath(layer) {
  const src = layer.regexp?.source || '';
  const literal = src
    .replace(/^\^/, '')
    .split(/[(?]/)[0]
    .replace(/\\\//g, '/')
    .replace(/\$$/, '');
  return literal === '' || literal === '/' ? '' : literal;
}

/** Join a mount prefix and a route path without producing `//`. */
const cleanPath = (value) => {
  const collapsed = ('/' + value).replace(/\/{2,}/g, '/');
  return collapsed.length > 1 ? collapsed.replace(/\/$/, '') : '/';
};

const endpoints = [];

function walk(stack, base) {
  for (const layer of stack) {
    if (layer.route) {
      const methods = Object.keys(layer.route.methods).filter((m) => layer.route.methods[m]);
      const permissions = new Set();
      let moduleKey = null;
      let authed = false;
      for (const h of layer.route.stack) {
        const fn = h.handle;
        if (fn?.permissions) fn.permissions.forEach((p) => permissions.add(p));
        if (fn?.module) moduleKey = fn.module;
        if (fn?.name === 'requireAuth' || fn?.guardName === 'requireAuth') authed = true;
      }
      endpoints.push({
        method: methods.join(', ').toUpperCase(),
        path: cleanPath(base + layer.route.path),
        permissions: [...permissions],
        module: moduleKey,
        authed,
      });
    } else if (layer.name === 'router' && layer.handle?.stack) {
      walk(layer.handle.stack, base + mountPath(layer));
    } else if (layer.name === 'mounted_app' && layer.handle?._router?.stack) {
      walk(layer.handle._router.stack, base + mountPath(layer));
    }
  }
}

walk(app._router.stack, '');

// Router-level guards (router.use(requireAuth, requireModule(...))) are not on
// the individual route layers, so resolve them from the parent stack.
function collectRouterGuards(stack, base, inherited) {
  for (const layer of stack) {
    if (layer.name === 'router' && layer.handle?.stack) {
      const prefix = base + mountPath(layer);
      const guards = { module: inherited.module, authed: inherited.authed };
      for (const l of layer.handle.stack) {
        if (l.name !== 'router' && !l.route) {
          if (l.handle?.module) guards.module = l.handle.module;
          if (l.handle?.name === 'requireAuth') guards.authed = true;
        }
      }
      for (const e of endpoints) {
        if (e.path.startsWith(prefix)) {
          if (!e.module && guards.module) e.module = guards.module;
          if (!e.authed && guards.authed) e.authed = true;
        }
      }
      collectRouterGuards(layer.handle.stack, prefix, guards);
    }
  }
}
collectRouterGuards(app._router.stack, '', { module: null, authed: false });

const groups = new Map();
for (const e of endpoints) {
  const key = cleanPath(e.path.split('/').slice(0, 3).join('/'));
  if (!groups.has(key)) groups.set(key, []);
  groups.get(key).push(e);
}

const lines = [];
lines.push('# API Reference');
lines.push('');
lines.push('> Generated by `npm run docs` from the live Express route table. Do not edit by hand.');
lines.push('');
lines.push(`Base path: \`/api\`. ${endpoints.length} endpoints.`);
lines.push('');
lines.push('## Conventions');
lines.push('');
lines.push('- **Auth** - `Authorization: Bearer <accessToken>` or the `erp_at` cookie set at login.');
lines.push('- **Tenant** - taken from the token. A platform admin may pass `X-Tenant-Id` to act on another tenant; every other caller is rejected.');
lines.push('- **Envelope** - single resources come back as `{ "data": ... }`, lists as `{ "data": [...], "meta": { "page", "limit", "total", "totalPages" } }`.');
lines.push('- **Errors** - `{ "error": { "code", "message", "details?" } }`. Codes in use: `VALIDATION_ERROR` (422), `UNAUTHORIZED` (401), `FORBIDDEN` (403), `MODULE_DISABLED` (403), `CONFLICT` (409), `NOT_FOUND` (404), `RATE_LIMITED` (429), `INTERNAL_ERROR` (500).');
lines.push('- **Permissions** - `<module>.<action>` keys from `shared/src/modules.js`. A caller needs every key listed for an endpoint.');
lines.push('- **Modules** - an endpoint whose module is disabled for the tenant returns 403 `MODULE_DISABLED`, regardless of permissions.');
lines.push('');

const moduleLabel = (key) => getModule(key)?.label;

for (const [group, items] of [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  const mod = items.find((i) => i.module)?.module;
  lines.push(`## \`${group}\`${mod ? ` - module: ${moduleLabel(mod) || mod}` : ''}`);
  lines.push('');
  lines.push('| Method | Path | Permission |');
  lines.push('| --- | --- | --- |');
  for (const e of items.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))) {
    const perm = e.permissions.length ? e.permissions.map((p) => `\`${p}\``).join(' or ') : e.authed ? '_authenticated_' : '_public_';
    lines.push(`| ${e.method} | \`${e.path}\` | ${perm} |`);
  }
  lines.push('');
}

const out = join(ROOT, 'docs', 'api.md');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join('\n'));
console.log(`wrote ${endpoints.length} endpoints to docs/api.md`);
